#!/bin/bash
# Document phase - Capture and document important learnings in CLAUDE.md

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}[ERROR]${NC} Not in a git repository"
    exit 1
fi

# Get current issue and criteria from TDD state
STATE_FILE=".tdd-state"
if [[ -f "$STATE_FILE" ]]; then
    source "$STATE_FILE"
else
    echo -e "${RED}[ERROR]${NC} No TDD state found. Run from within TDD workflow."
    exit 1
fi

# Function to prompt for documentation
prompt_documentation() {
    local prompt="$1"
    local response=""
    
    echo -e "\n${BLUE}$prompt${NC}"
    echo "Press Enter twice when done (empty line to finish):"
    
    while IFS= read -r line; do
        [[ -z "$line" ]] && break
        response="${response}${line}\n"
    done
    
    echo "$response"
}

# Function to format documentation entry
format_documentation_entry() {
    local category="$1"
    local content="$2"
    local issue="$3"
    local date=$(date +"%Y-%m-%d")
    
    if [[ -n "$content" && "$content" != "\n" ]]; then
        cat <<EOF

### $category (Issue #$issue - $date)
$content
EOF
    fi
}

# Main documentation collection
echo -e "${GREEN}📝 DOCUMENT Phase - Capture project learnings${NC}"
echo -e "${BLUE}Issue #$ISSUE - Criteria $CRITERIA${NC}\n"

# Collect documentation
patterns=$(prompt_documentation "What new patterns or conventions were established?")
gotchas=$(prompt_documentation "Any important edge cases or gotchas discovered?")
practices=$(prompt_documentation "Project-specific best practices to document?")
tools=$(prompt_documentation "Tool usage recommendations or tips?")
architecture=$(prompt_documentation "Architecture decisions or design patterns?")

# Check if any documentation was provided
if [[ -z "$patterns" && -z "$gotchas" && -z "$practices" && -z "$tools" && -z "$architecture" ]]; then
    echo -e "\n${YELLOW}[INFO]${NC} No documentation provided. Skipping DOCUMENT phase."
    exit 0
fi

# Prepare documentation content
doc_content=""

# Add a new section header if this is the first documentation for this issue
doc_content+="\n## Issue #$ISSUE Documentation\n"

# Add each category if content was provided
[[ -n "$patterns" && "$patterns" != "\n" ]] && \
    doc_content+=$(format_documentation_entry "Patterns & Conventions" "$patterns" "$ISSUE")

[[ -n "$gotchas" && "$gotchas" != "\n" ]] && \
    doc_content+=$(format_documentation_entry "Edge Cases & Gotchas" "$gotchas" "$ISSUE")

[[ -n "$practices" && "$practices" != "\n" ]] && \
    doc_content+=$(format_documentation_entry "Best Practices" "$practices" "$ISSUE")

[[ -n "$tools" && "$tools" != "\n" ]] && \
    doc_content+=$(format_documentation_entry "Tool Usage" "$tools" "$ISSUE")

[[ -n "$architecture" && "$architecture" != "\n" ]] && \
    doc_content+=$(format_documentation_entry "Architecture Decisions" "$architecture" "$ISSUE")

# Update CLAUDE.md
CLAUDE_FILE="CLAUDE.md"
if [[ ! -f "$CLAUDE_FILE" ]]; then
    echo -e "${RED}[ERROR]${NC} CLAUDE.md not found"
    exit 1
fi

# Show preview
echo -e "\n${BLUE}Preview of documentation to be added:${NC}"
echo -e "$doc_content"

# Confirm before updating
echo -e "\n${YELLOW}Add this documentation to CLAUDE.md? (y/n)${NC}"
read -r confirm
if [[ "$confirm" != "y" ]]; then
    echo -e "${YELLOW}[INFO]${NC} Documentation cancelled."
    exit 0
fi

# Append to CLAUDE.md
echo -e "$doc_content" >> "$CLAUDE_FILE"

# Stage and commit the documentation
git add "$CLAUDE_FILE"
git commit -m "docs: add development learnings from issue #$ISSUE

- Document patterns, gotchas, and best practices discovered
- Capture project-specific guidance for future development
- Update CLAUDE.md with issue #$ISSUE learnings

Generated by DOCUMENT phase"

echo -e "\n${GREEN}✅ Documentation added to CLAUDE.md and committed${NC}"
echo -e "${BLUE}ℹ️  Remember to push changes when ready${NC}"