// Configuration types

export interface WorkFloConfig {
  PERSONA: string;
  CONFIDENCE_WEIGHTS_TEST_PASS: number;
  CONFIDENCE_WEIGHTS_COVERAGE: number;
  CONFIDENCE_WEIGHTS_REVIEW: number;
  CONFIDENCE_WEIGHTS_MUTATION: number;
  CONFIDENCE_THRESHOLD: number;
  MUTATION_THRESHOLD: number;
  LARGE_CHANGE_THRESHOLD: number;
  SMALL_CHANGE_THRESHOLD: number;
  QUALITY_BASE_SCORE: number;
  QUALITY_TEST_BONUS: number;
  QUALITY_TODO_PENALTY: number;
  QUALITY_LARGE_CHANGE_PENALTY: number;
  QUALITY_SMALL_CHANGE_BONUS: number;
  AI_REVIEW_RETRY_ATTEMPTS: number;
  AI_REVIEW_TIMEOUT: number;
  GIT_CACHE_ENABLED: boolean;
  GIT_CACHE_TTL: number;
}