#!/bin/bash
# create-migration-epic.sh - Create complete bash-to-WorkFlo migration epic with all issues

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[EPIC-CREATOR]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

# Check if gh CLI is authenticated
if ! gh auth status >/dev/null 2>&1; then
    error "GitHub CLI not authenticated. Run 'gh auth login' first."
fi

# Array to store created issue numbers
declare -a created_issues=()

# Function to create issue and store number
create_issue() {
    local title="$1"
    local body="$2"
    local labels="$3"
    
    log "Creating: $title"
    
    local issue_url
    issue_url=$(gh issue create --title "$title" --body "$body" --label "$labels")
    
    local issue_number
    issue_number=$(echo "$issue_url" | grep -o '[0-9]*$')
    
    if [[ -n "$issue_number" ]]; then
        created_issues+=("$issue_number")
        success "Created issue #$issue_number"
        echo "$issue_number"
    else
        error "Failed to create issue: $title"
    fi
}

log "Creating Bash-to-WorkFlo Migration Epic and Issues..."

# Create Epic
epic_body="## 🎯 Epic Overview

Complete migration from bash scripts to native WorkFlo CLI commands by enhancing existing Commands. Each slice delivers complete end-to-end value with comprehensive test coverage.

## 🚀 Goal
Achieve true dogfooding where WorkFlo manages its own development workflow.

## 📋 Vertical Slices
1. **Quality Workflow**: ./qc → workflo quality
2. **Start Workflow**: ./sw → workflo start  
3. **Validation Workflow**: hooks → workflo validate
4. **TDD Workflow**: ./tdd → workflo tdd

## ✅ Success Criteria
- Zero bash workflow scripts remain
- All development workflow managed through WorkFlo
- WorkFlo development visible in WorkFlo UI
- Performance equal or better than bash scripts
- Complete dogfooding achieved

## 🔗 Dependencies
This epic depends on completing all feature slices and their associated test issues.

---
🤖 *Generated by WorkFlo Migration Script*"

epic_number=$(create_issue "Epic: Complete Bash-to-WorkFlo Migration (Dogfooding Implementation)" "$epic_body" "epic,type: feature,area: cli,priority: high")

# Slice 1: Quality Workflow
slice1_body="## 🎯 Feature Overview
Enhance QualityCommand.cs to replace pr-quality-check.sh logic and create ./qc wrapper script.

## 📋 Acceptance Criteria
- All pr-quality-check.sh functionality moved to native .NET
- ./qc wrapper maintains backward compatibility
- No bash subprocess calls for quality operations
- HTML report generation works identically

## 🧪 Test Dependencies
This feature depends on ALL test issues in the slice-1 milestone being resolved:
- Test 1.1: QualityCommand builds solution natively
- Test 1.2: QualityCommand runs tests natively  
- Test 1.3: QualityCommand analyzes coverage natively
- Test 1.4: QualityCommand checks code formatting natively
- Test 1.5: QualityCommand generates HTML report
- Test 1.6: QualityCommand returns correct exit codes
- Test 1.7: ./qc wrapper script maintains compatibility

## 🔗 Epic
Related to Epic #$epic_number

---
🤖 *Generated by WorkFlo Migration Script*"

slice1_number=$(create_issue "Slice 1: Complete Quality Workflow Migration" "$slice1_body" "type: feature,area: cli,priority: high,size: large")

# Test issues for Slice 1
test_issues=(
    "Test 1.1: QualityCommand builds solution natively|dotnet workflo quality check runs dotnet build without subprocess calls. Must use native .NET APIs for build operations.|test,area: cli,priority: high,size: small"
    "Test 1.2: QualityCommand runs tests natively|dotnet workflo quality check runs dotnet test without subprocess calls. Must use native .NET test runner APIs.|test,area: testing,priority: high,size: small"
    "Test 1.3: QualityCommand analyzes coverage natively|Coverage analysis using .NET APIs, no shell parsing of XML files. Must parse coverage.cobertura.xml programmatically.|test,area: testing,priority: high,size: small"
    "Test 1.4: QualityCommand checks code formatting natively|dotnet format verification using .NET APIs. Must integrate dotnet format without subprocess calls.|test,area: cli,priority: high,size: small"
    "Test 1.5: QualityCommand generates HTML report|HTML report identical to pr-quality-check.sh output format. Must match existing report structure exactly.|test,area: cli,priority: high,size: medium"
    "Test 1.6: QualityCommand returns correct exit codes|0=pass, 1=fail, 2=warnings matching pr-quality-check.sh behavior exactly. Must maintain compatibility.|test,area: cli,priority: high,size: small"
    "Test 1.7: ./qc wrapper script maintains compatibility|All CLAUDE.md references to ./qc work unchanged. Wrapper must pass through all arguments correctly.|test,area: cli,priority: high,size: small"
)

log "Creating test issues for Slice 1..."
for test_item in "${test_issues[@]}"; do
    IFS='|' read -r title body labels <<< "$test_item"
    
    test_body="## 🧪 Test Specification

$body

## ✅ Acceptance Criteria
- Implementation passes this specific test
- No regressions in existing functionality
- Performance meets or exceeds bash script equivalent

## 🔗 Feature Dependency
This test must pass for Slice 1 Feature #$slice1_number to be considered complete.

## 🔗 Epic
Related to Epic #$epic_number

---
🤖 *Generated by WorkFlo Migration Script*"
    
    create_issue "$title" "$test_body" "$labels" >/dev/null
done

success "Created Epic #$epic_number with Slice 1 feature and 7 test issues"
log "Total issues created: ${#created_issues[@]}"
log "Issue numbers: ${created_issues[*]}"

echo ""
echo "Next steps:"
echo "1. Create remaining slices with: ./scripts/create-migration-slices.sh"
echo "2. Start work on Slice 1: ./gb start $slice1_number" 
echo "3. Use GitHub project board to track progress"